### PR TITLE
Introducing lift delete button

### PR DESCRIPTION
**Pull request by TanJunKiat**
Continuation of #509 

### Implementation summary
- Delete button in `lift_table` to remove lift from map and yam
- Delete any lift cabin way point and any edges connected to said way point

### CODE REVIEW

**Review by luca-della-vedova — COMMENTED** [review]
Interesting, I was thinking something a lot simpler (just iterating over waypoints and removing the `lift_cabin` property if it matches the deleted lift name, leaving everything else intact) but I can see why it could be helpful to automatically remove the lift vertices and edges that lead into the lift.
I'm very slightly concerned about [this break](https://github.com/TanJunKiat/rmf_traffic_editor/blob/7a55fbd1d695059f3ee5bc40a4601cbb2c27c9f3/rmf_traffic_editor/gui/level.cpp#L510), this will mean that as soon as one waypoint with the matching `lift_cabin` property is found it will stop iterating, which "might" behave unexpectedly if there are more waypoints with that property, which will not be cleaned up properly. Now this is usually not the case but other parts of the code dealing with such property don't have the assumption that there will never be more than one (i.e. here https://github.com/TanJunKiat/rmf_traffic_editor/blob/7a55fbd1d695059f3ee5bc40a4601cbb2c27c9f3/rmf_traffic_editor/gui/lift_dialog.cpp#L441-L449, you can see that a flag is set to denote it as found but the loop doesn't early exit).

**Comment by luca-della-vedova** [comment]
The test failures seem mostly related to uncrustify, you should be able to reproduce with a local `colcon test` run

**Comment by TanJunKiat** [comment]
Right now the implementation is a nested `if` , to check for a `lift_cabin` property, then check if the lift name matches.

I am also worried on the situation where the lift cabin name is changed manually via the property panel which results in unsuccessful deletion of the vertex after deleting the lift.

**Comment by luca-della-vedova** [comment]
Yap I know there are two nested if statements to make sure the lift matches, it's more a "what would happen if there was more than one lift with the requested `lift_name`?", the main other code path I linked would still work but this wouldn't because only the first waypoint would be cleaned up

**Comment by TanJunKiat** [comment]
Alright, what we can do is do remove the `break` and remove all the waypoints that fits the criteria.

**Review by luca-della-vedova — DISMISSED** [review]
Thanks for iterating!

**Comment by luca-della-vedova** [comment]
Ah sorry last hurdle, we need commits to be signed https://docs.github.com/authentication/managing-commit-signature-verification/about-commit-signature-verification, can you do that and force-push to this PR?

**Review by luca-della-vedova — APPROVED** [review]

**Comment by TanJunKiat** [comment]
Sorry, still trying to fumble around with the signature. Will get to it asap.

**Review by luca-della-vedova — DISMISSED** [review]

**Review by luca-della-vedova — APPROVED** [review]

**Comment by luca-della-vedova** [comment]
Thanks for iterating! (Sign offs can be painful the first time :) )

**Pull request merged**
